---
image: docker:18.01.0-ce-git
services:
  - docker:18.01.0-ce-dind
stages:
  - build
  - deploy

variables:
  REDELIVRE_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

## Homolog

build to homolog:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t $REDELIVRE_RELEASE_IMAGE --build-arg REDELIVRE_SSH_PASSPHRASE=$REDELIVRE_SSH_PASSPHRASE --build-arg REDELIVRE_SSH_PRIVATE=$REDELIVRE_SSH_PRIVATE --build-arg WORDPRESS_UPGRADE_PASS=$WORDPRESS_UPGRADE_PASS --build-arg WORDPRESS_UPGRADE_USER=$WORDPRESS_UPGRADE_USER .
    - docker push $REDELIVRE_RELEASE_IMAGE
  only:
    - /docker/
  environment: homolog
  tags:
    - docker

      #deploy to homolog:
      #  stage: deploy
      #  image: cdrx/rancher-gitlab-deploy
      #  script:
      #    - upgrade --environment RedeLivre --stack redelivre-site-beta --service wordpress --no-finish-upgrade --debug --rancher-url $RANCHER_URL --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY
      #  only:
      #    - /docker/
      #  environment: homolog
      #  tags:
      #    - docker
