version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
       - REDELIVRE_SSH_PASSPHRASE=some_key_pass
       - REDELIVRE_SSH_PRIVATE=some_ssh_key
       - WORDPRESS_UPGRADE_PASS=some_pass
       - WORDPRESS_UPGRADE_USER=some_user
       - DOSEmailNotify=some_email
       - DOSSystemCommand=some_command
    env_file:
     - ./Docker/.wp_env
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DOMAIN_CURRENT_SITE=redelivre.localhost
      - WORDPRESS_DEBUG=true
      - WORDPRESS_WP_DEBUG_DISPLAY: 'false'
      - WP_AUTH_KEY: '1234567890123456789012345678901234567890123456789012345678901234'
      - WP_AUTH_SALT: '1234567890123456789012345678901234567890123456789012345678901235'
      - WP_LOGGED_IN_KEY: '1234567890123456789012345678901234567890123456789012345678901236'
      - WP_LOGGED_IN_SALT: '1234567890123456789012345678901234567890123456789012345678901237'
      - WP_NONCE_KEY: '1234567890123456789012345678901234567890123456789012345678901238'
      - WP_NONCE_SALT: '1234567890123456789012345678901234567890123456789012345678901239'
      - WP_SECURE_AUTH_KEY: '1234567890123456789012345678901234567890123456789012345678901230'
      - WP_SECURE_AUTH_SALT: '1234567890123456789012345678901234567890123456789012345678901231'
    volumes:
      - ./volumes/web/wp-config.d:/var/www/html/wp-config.d
      - ./volumes/web/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./volumes/web/wp-content/blogs.dir:/var/www/html/wp-content/blogs.dir
      - ./volumes/web/wp-content/cache:/var/www/html/wp-content/cache
      - ./volumes/web/wp-content/plugins/si-captcha-for-wordpress/captcha/cache:/var/www/html/wp-content/plugins/si-captcha-for-wordpress/captcha/cache
      - ./volumes/web/wp-content/plugins/si-captcha-for-wordpress/captcha/temp:/var/www/html/wp-content/plugins/si-captcha-for-wordpress/captcha/temp
      - ./volumes/web/htaccess_prod:/var/www/html/.htaccess
      - ./volumes/web/mpm_prefork.conf:/etc/apache2/mods-enabled/mpm_prefork.conf
      - ./volumes/web/custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    depends_on:
      - mariadb
    ports:
      - "8880:80"
      - "4443:443"
    labels:
      traefik.port: '80'
      traefik.frontend.rule: HostRegexp:{catchall:.*}
      # traefik.frontend.redirect.replacement: https://$2
      # traefik.frontend.redirect.regex: ^https://www.(.*)
      traefik.frontend.priority: '1'
      traefik.enable: 'true'
    restart: unless-stopped

  mariadb:
    image: mariadb:10
    env_file:
     - ./Docker/.db_env
    environment:
      - MYSQL_ROOT_PASSWORD=rootpasswd
      - MYSQL_USER=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=wordpress
      - TERM=xterm
    volumes:
      - ./volumes/mysql/mysql:/var/lib/mysql
      - ./volumes/mysql/backups:/var/backups
      - ./volumes/mysql/my.cnf:/etc/mysql/my.cnf
    restart: unless-stopped
    ports:
      - "3306:3306"

  traefik:
    image: traefik:alpine
    environment:
      AWS_ACCESS_KEY_ID: xxxxxxx
      AWS_SECRET_ACCESS_KEY: xxxxxx
      AWS_REGION: us-east-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/traefik/traefik.toml:/traefik.toml"
    ports:
    - 80:80
    - 8080:8080
    - 443:443
    command:
    - --configfile=/traefik.toml
    labels:
      traefik.frontend.rule: Host:traefik.redelivre
      traefik.alias: traefik
      traefik.port: '8080'
      traefik.enable: 'true'
    restart: unless-stopped

  portainer:
    image: portainer/portainer
    volumes:
      - ./volumes/portainer/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    ports:
      - 9000
    labels:
      traefik.frontend.rule: Host:portainer.redelivre
      traefik.port: '9000'
      traefik.enable: 'true'
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    volumes:
      - ./volumes/phpmyadmin/sessions:/sessions
      - ./volumes/phpmyadmin/htaccess:/var/www/html/.htaccess
      - ./volumes/phpmyadmin/users.passwd:/etc/apache2/users.passwd
    labels:
      traefik.frontend.rule: Host:phpmyadmin.redelivre
      traefik.frontend.priority: '1'
      traefik.port: '80'
      traefik.enable: 'true'
      traefik.docker.network: 'web'
      traefik.frontend.redirect.entryPoint: 'https'
