debug = true 

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
#     [entryPoints.http.redirect]
#     entryPoint = "https"
#   [entryPoints.https]
#   address = ":443"
#   [entryPoints.https.tls]

[retry]
[api]
[ping]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "bonde.devel"
watch = true
exposedbydefault = false


