<?php
$states = array(
		"INSERT INTO `states` VALUES (11,'Rondônia','RO');",
		"INSERT INTO `states` VALUES (12,'Acre','AC');",
		"INSERT INTO `states` VALUES (13,'Amazonas','AM');",
		"INSERT INTO `states` VALUES (14,'Roraima','RR');",
		"INSERT INTO `states` VALUES (15,'Pará','PA');",
		"INSERT INTO `states` VALUES (16,'Amapá','AP');",
		"INSERT INTO `states` VALUES (17,'Tocantins','TO');",
		"INSERT INTO `states` VALUES (21,'Maranhão','MA');",
		"INSERT INTO `states` VALUES (22,'Piauí','PI');",
		"INSERT INTO `states` VALUES (23,'Ceará','CE');",
		"INSERT INTO `states` VALUES (24,'Rio Grande do Norte','RN');",
		"INSERT INTO `states` VALUES (25,'Paraíba','PB');",
		"INSERT INTO `states` VALUES (26,'Pernambuco','PE');",
		"INSERT INTO `states` VALUES (27,'Alagoas','AL');",
		"INSERT INTO `states` VALUES (28,'Sergipe','SE');",
		"INSERT INTO `states` VALUES (29,'Bahia','BA');",
		"INSERT INTO `states` VALUES (31,'Minas Gerais','MG');",
		"INSERT INTO `states` VALUES (32,'Espírito Santo','ES');",
		"INSERT INTO `states` VALUES (33,'Rio de Janeiro','RJ');",
		"INSERT INTO `states` VALUES (35,'São Paulo','SP');",
		"INSERT INTO `states` VALUES (41,'Paraná','PR');",
		"INSERT INTO `states` VALUES (42,'Santa Catarina','SC');",
		"INSERT INTO `states` VALUES (43,'Rio Grande do Sul','RS');",
		"INSERT INTO `states` VALUES (50,'Mato Grosso do Sul','MS');",
		"INSERT INTO `states` VALUES (51,'Mato Grosso','MT');",
		"INSERT INTO `states` VALUES (52,'Goiás','GO');",
		"INSERT INTO `states` VALUES (53,'Distrito Federal','DF');"
);